#INPUT A NUMBER AND CHECK WHETHER THE NUMBER IS DIVISIBLE BY BOTH 2 AND 3
a=int(input("ENTER A NUMBER: "))

if a%2==0 and a%3==0:
    print("THE INPUTTED NUMBER IS DIVISIBLE BY 2 AND 3")
else:
    print("THE INPUTTED NUMBER IS NOT DIVISIBLE BY 2 AND 3")    